<?php

class toba_mc_comp__37
{
	static function get_metadatos()
	{
		return array (
  'molde' => 
  array (
    'proyecto' => 'comunidades',
    'molde' => '37',
    'operacion_tipo' => '10',
    'nombre' => 'SacramentosPersona',
    'item' => '3506',
    'carpeta_archivos' => 'sacramentospersona',
    'prefijo_clases' => '_sacramentospersona',
    'fuente' => 'comunidades',
    'clase' => 'toba_asistente_abms',
  ),
  'molde_abms' => 
  array (
    'proyecto' => 'comunidades',
    'molde' => '37',
    'tabla' => 'sacramentospersona',
    'gen_usa_filtro' => 1,
    'gen_separar_pantallas' => 1,
    'cuadro_eof' => NULL,
    'cuadro_id' => 'id_sacramentopersona',
    'filtro_comprobar_parametros' => 0,
    'cuadro_forzar_filtro' => 1,
    'cuadro_eliminar_filas' => 0,
    'cuadro_carga_origen' => 'datos_tabla',
    'cuadro_carga_sql' => 'SELECT
	t_s.id_sacramentopersona,
	t_p.nombres as id_persona_nombre,
	t_s1.sacramento as id_sacramento_nombre,
	t_c.comunidad as id_comunidad_nombre,
	t_t.templo as id_templo_nombre,
	t_s.fechasacramento
FROM
	sacramentospersona as t_s	LEFT OUTER JOIN templos as t_t ON (t_s.id_templo = t_t.id_templo),
	personas as t_p,
	sacramentos as t_s1,
	comunidades as t_c
WHERE
		t_s.id_persona = t_p.id_persona
	AND  t_s.id_sacramento = t_s1.id_sacramento
	AND  t_s.id_comunidad = t_c.id_comunidad',
    'cuadro_carga_php_include' => NULL,
    'cuadro_carga_php_clase' => NULL,
    'cuadro_carga_php_metodo' => NULL,
    'datos_tabla_validacion' => NULL,
    'apdb_pre' => NULL,
  ),
  'molde_abms_fila' => 
  array (
    0 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '199',
      'orden' => '1',
      'columna' => 'id_sacramentopersona',
      'etiqueta' => 'Id Sacramentopersona',
      'en_cuadro' => 0,
      'en_form' => 0,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => '0',
      'cuadro_formato' => '7',
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => 'sacramentospersona_id_sacramentopersona_seq',
      'dt_pk' => 1,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    1 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '200',
      'orden' => '2',
      'columna' => 'id_persona',
      'etiqueta' => 'Id Persona',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => '4',
      'cuadro_formato' => '1',
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id_persona, nombres FROM personas ORDER BY nombres',
      'ef_carga_tabla' => 'personas',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id_persona',
      'ef_carga_col_desc' => 'nombres',
    ),
    2 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '201',
      'orden' => '3',
      'columna' => 'id_sacramento',
      'etiqueta' => 'Id Sacramento',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => '4',
      'cuadro_formato' => '1',
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id_sacramento, sacramento FROM sacramentos ORDER BY sacramento',
      'ef_carga_tabla' => 'sacramentos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id_sacramento',
      'ef_carga_col_desc' => 'sacramento',
    ),
    3 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '202',
      'orden' => '4',
      'columna' => 'id_comunidad',
      'etiqueta' => 'Id Comunidad',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => '4',
      'cuadro_formato' => '1',
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id_comunidad, comunidad FROM comunidades ORDER BY comunidad',
      'ef_carga_tabla' => 'comunidades',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id_comunidad',
      'ef_carga_col_desc' => 'comunidad',
    ),
    4 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '203',
      'orden' => '5',
      'columna' => 'id_templo',
      'etiqueta' => 'Id Templo',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => '4',
      'cuadro_formato' => '1',
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id_templo, templo FROM templos ORDER BY templo',
      'ef_carga_tabla' => 'templos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id_templo',
      'ef_carga_col_desc' => 'templo',
    ),
    5 => 
    array (
      'proyecto' => 'comunidades',
      'molde' => '37',
      'fila' => '204',
      'orden' => '6',
      'columna' => 'fechasacramento',
      'etiqueta' => 'Fechasacramento',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => '7',
      'cuadro_formato' => '8',
      'dt_tipo_dato' => 'F',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_fecha',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
  ),
);
	}

}

?>