<?php

class toba_mc_comp__2494
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'comunidades',
    'objeto' => '2494',
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_personas',
    'subclase_archivo' => 'datos/dt_personas.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'personas',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'comunidades',
    'fuente' => 'comunidades',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2015-01-15 13:51:50',
    'punto_montaje' => '16',
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => NULL,
    'cant_dependencias' => '0',
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'personas',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => '1',
    'punto_montaje' => NULL,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => NULL,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => NULL,
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '971',
      'columna' => 'id_persona',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'personas_id_persona_seq',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    1 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '972',
      'columna' => 'id_comunidad',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    2 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '973',
      'columna' => 'nombres',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    3 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '974',
      'columna' => 'apellido',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    4 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '975',
      'columna' => 'nrodocumento',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    5 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '976',
      'columna' => 'fechanacimiento',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    6 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '977',
      'columna' => 'direccion',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 60,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    7 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '978',
      'columna' => 'id_barrio',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    8 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '979',
      'columna' => 'id_tipodocumento',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    9 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '980',
      'columna' => 'nrotelcelular',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    10 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '981',
      'columna' => 'nrotelfijo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    11 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '982',
      'columna' => 'estado',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 5,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    12 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '983',
      'columna' => 'fechaingreso',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
    13 => 
    array (
      'objeto_proyecto' => 'comunidades',
      'objeto' => '2494',
      'col_id' => '984',
      'columna' => 'email',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 80,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => NULL,
      'tabla' => 'personas',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>